-- Generated by scripts/generate_capacity_lean_traces.py; do not edit.
import CapacityCore.Accounting
open CapacityCore

def before0 : State := { unfinished := 3, completed := 0, available := 3, reserved := 0, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [] }
def after0 : State := { unfinished := 3, completed := 0, available := 0, reserved := 3, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [] }
example : reserve before0 3 = some after0 := by decide

def before1 : State := { unfinished := 3, completed := 0, available := 3, reserved := 0, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [] }
def after1 : State := { unfinished := 3, completed := 0, available := 0, reserved := 3, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [] }
example : reserve before1 3 = some after1 := by decide

def before2 : State := { unfinished := 3, completed := 0, available := 0, reserved := 3, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [] }
def after2 : State := { unfinished := 3, completed := 0, available := 0, reserved := 3, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [] }
example : some before2 = some after2 := by decide

def before3 : State := { unfinished := 3, completed := 0, available := 0, reserved := 3, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [] }
def after3 : State := { unfinished := 3, completed := 0, available := 0, reserved := 3, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [] }
example : some before3 = some after3 := by decide

def before4 : State := { unfinished := 3, completed := 0, available := 0, reserved := 3, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [] }
def after4 : State := { unfinished := 3, completed := 0, available := 0, reserved := 3, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [] }
example : some before4 = some after4 := by decide

def before5 : State := { unfinished := 3, completed := 0, available := 0, reserved := 3, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [] }
def after5 : State := { unfinished := 3, completed := 0, available := 0, reserved := 3, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [] }
example : some before5 = some after5 := by decide

def before6 : State := { unfinished := 3, completed := 0, available := 0, reserved := 3, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [] }
def after6 : State := { unfinished := 2, completed := 1, available := 1, reserved := 2, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [0] }
example : (finish before6 0 1 0 []).bind (fun s => releaseUnused s 1) = some after6 := by decide

def before7 : State := { unfinished := 3, completed := 0, available := 0, reserved := 3, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [] }
def after7 : State := { unfinished := 2, completed := 1, available := 0, reserved := 2, consumed := 1, authority := 0, residuals := [0, 1, 2], seen := [0] }
example : (finish before7 0 1 1 []).bind (fun s => releaseUnused s 0) = some after7 := by decide

def before8 : State := { unfinished := 2, completed := 1, available := 1, reserved := 2, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [0] }
def after8 : State := { unfinished := 3, completed := 1, available := 1, reserved := 2, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [0] }
example : some (followup before8 1) = some after8 := by decide

def before9 : State := { unfinished := 2, completed := 1, available := 0, reserved := 2, consumed := 1, authority := 0, residuals := [0, 1, 2], seen := [0] }
def after9 : State := { unfinished := 3, completed := 1, available := 0, reserved := 2, consumed := 1, authority := 0, residuals := [0, 1, 2], seen := [0] }
example : some (followup before9 1) = some after9 := by decide

def before10 : State := { unfinished := 3, completed := 1, available := 1, reserved := 2, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [0] }
def after10 : State := { unfinished := 3, completed := 1, available := 1, reserved := 2, consumed := 0, authority := 0, residuals := [0, 1, 2], seen := [0] }
example : (finish before10 0 0 0 []).bind (fun s => releaseUnused s 0) = some after10 := by decide

def before11 : State := { unfinished := 3, completed := 1, available := 0, reserved := 2, consumed := 1, authority := 0, residuals := [0, 1, 2], seen := [0] }
def after11 : State := { unfinished := 3, completed := 1, available := 0, reserved := 2, consumed := 1, authority := 0, residuals := [0, 1, 2], seen := [0] }
example : (finish before11 0 0 0 []).bind (fun s => releaseUnused s 0) = some after11 := by decide
