"""Generate Lean equality checks from an actual Python runtime/reducer history."""

from pathlib import Path

from verification_ecology_kit.capacity.examples import scenario
from verification_ecology_kit.capacity.formal import trace
from verification_ecology_kit.capacity.reducer import synthetic_result
from verification_ecology_kit.capacity.runtime import CapacityRuntime
from verification_ecology_kit.runtime.in_memory import InMemoryStore


def main() -> None:
    c, ecology = scenario("negative")
    runtime = CapacityRuntime(InMemoryStore(ecology), c)
    allocation = runtime.plan()
    runtime.event("apply", allocation, "apply")
    aid = next(key for key, slot in allocation["schedule"].items() if slot == 0)
    runtime.event("dispatch", {"action_id": aid, "reason": "finite fixture"}, "dispatch")
    result = synthetic_result(c, runtime.inspect(), aid, "negative")
    result["costs"] = [0, 1]
    runtime.event("tick", {"slot": 1}, "tick")
    runtime.event("result", result, "result")
    runtime.event("result", result, "retry")
    rows = trace(c, runtime.store.load().archive["capacity_v1"]["events"])
    lines = [
        "-- Generated by scripts/generate_capacity_lean_traces.py; do not edit.",
        "import CapacityCore.Accounting",
        "open CapacityCore",
        "",
    ]
    seen = dict.fromkeys(range(len(c.resources)), False)
    for index, row in enumerate(rows):
        before, after = row["before"], row["after"]
        coord = row["coordinate"]
        prior_seen = seen[coord]
        if row["event"] == "result":
            seen[coord] = True

        def record(value, processed):
            fields = ", ".join(f"{key} := {quantity}" for key, quantity in value.items())
            return (
                "{ "
                + fields
                + ", residuals := [0, 1, 2], seen := "
                + ("[0]" if processed else "[]")
                + " }"
            )

        lines.extend(
            [
                f"def before{index} : State := {record(before, prior_seen)}",
                f"def after{index} : State := {record(after, seen[coord])}",
            ]
        )
        if row["event"] == "apply":
            amount = after["reserved"] - before["reserved"]
            expression = f"reserve before{index} {amount}"
        elif row["event"] == "followup":
            expression = f"some (followup before{index} {row['arrivals']})"
        elif row["event"] == "result":
            units = after["completed"] - before["completed"]
            cost = after["consumed"] - before["consumed"]
            unused = before["reserved"] - after["reserved"] - cost
            expression = (
                f"(finish before{index} 0 {units} {cost} []).bind "
                f"(fun s => releaseUnused s {unused})"
            )
        else:
            expression = f"some before{index}"
        lines.append(f"example : {expression} = some after{index} := by decide")
        lines.append("")
    target = Path(__file__).resolve().parents[1] / "formal/lean/CapacityCore/Conformance.lean"
    target.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
